#!/bin/bash

# Install gnome terminal color scheme
sessionfile=`find "${HOME}/.dbus/session-bus/" -type f`
export `grep "DBUS_SESSION_BUS_ADDRESS" "${sessionfile}" | sed '/^#/d'`

gconftool-2 --load gnome-terminal-conf.xml 

# Install dotfiles
dir=~/dotfiles
files="bashrc haskeline inputrc tmux.conf vimrc"
mkdir -p old
for file in $files; do
    mv ~/.$file old
    ln -s $dir/$file ~/.$file
done

# Install vundle
git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle
vim +BundleInstall +qall
